// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHPEHBLPiWJjjLDak6qLgV0vfhhmLFMok',
    appId: '1:475221928257:web:f4a4a83ef8e24734a219c0',
    messagingSenderId: '475221928257',
    projectId: 'inteligence-artificial-app',
    authDomain: 'inteligence-artificial-app.firebaseapp.com',
    storageBucket: 'inteligence-artificial-app.appspot.com',
    measurementId: 'G-H4SW94CT2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGFzkP7y5K1p-2G71xJGmQ-TX-Y8pZLvU',
    appId: '1:475221928257:android:19aa3090ecf4ec54a219c0',
    messagingSenderId: '475221928257',
    projectId: 'inteligence-artificial-app',
    storageBucket: 'inteligence-artificial-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgxiTNrGlOuEyE2xtcohKVDBTk-qznYk0',
    appId: '1:475221928257:ios:666580cc44ee5f25a219c0',
    messagingSenderId: '475221928257',
    projectId: 'inteligence-artificial-app',
    storageBucket: 'inteligence-artificial-app.appspot.com',
    iosClientId: '475221928257-he1rovevbc466n5vu4tef8763vog5dcu.apps.googleusercontent.com',
    iosBundleId: 'com.example.inteligenceArtificialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgxiTNrGlOuEyE2xtcohKVDBTk-qznYk0',
    appId: '1:475221928257:ios:666580cc44ee5f25a219c0',
    messagingSenderId: '475221928257',
    projectId: 'inteligence-artificial-app',
    storageBucket: 'inteligence-artificial-app.appspot.com',
    iosClientId: '475221928257-he1rovevbc466n5vu4tef8763vog5dcu.apps.googleusercontent.com',
    iosBundleId: 'com.example.inteligenceArtificialApp',
  );
}
